---
- name: configure nextjs server
  become: true
  become_user: root
  hosts: app
  roles:
    - docker
    - nextjs
    - promtail

- name: configure grafana
  become: true
  become_user: root
  hosts: monitoring
  roles:
    - docker
    - grafana
    - prometheus  
    - loki
