---
# tasks for server side
- name: OpenVPN | Install required packages for openvpn
  apt:
    name:
      - openvpn
      - easy-rsa
      - iptables-persistent
    update_cache: true
    state: present
  notify:
   - enable openvpn

- name: OpenVPN | Enable ipv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
    ignoreerrors: true
  failed_when: false
  
- name: "OpenVPN | ensure {{ openvpn_dir }}/easy-rsa exitst"
  file:
    path: "{{ openvpn_dir}}/easy-rsa"
    state: directory
    mode: 075

- name: OpenVPN | create vars file
  copy:
    dest: "{{ openvpn_easyrsa_dir }}/vars"
    content: | 
      set_var EASYRSA_ALGO "ec"
      set_var EASYRSA_DIGEST "sha512"

- name: OpenVPN | easy-rsa init-pki    
  command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa init-pki"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/pki"

- name: OpenVPN | easy-rsa build-ca    
  command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa build-ca nopass"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/pki/ca.crt"
  environment:
    EASYRSA_BATCH: "yes"

- name: OpenVPN | easy-rsa gen dh    
  command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa gen-dh"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/pki/dh.pem"

## server
- name: OpenVPN | easy-rsa server nopass    
  command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa build-server-full server nopass"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/pki/issued/server.crt"

#clients
- name: OpenVPN | easy-rsa clients nopass    
  command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa build-client-full {{ item }} nopass"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/pki/issued/{{ item }}.crt"
  with_items:
    - "{{ openvpn_clients }}"

- name: OpenVPN | easy-rsa gen-crl
  command:
    cmd: "{{ openvpn_easyrsa_dir }}/easyrsa gen-crl"
    chdir: "{{ openvpn_dir }}/easy-rsa"
    creates: "{{ openvpn_dir }}/easy-rsa/pki/crl.pem"

- name: OpenVPN | openvpn genkey
  command:
    cmd: "openvpn --genkey --secret {{ openvpn_dir }}/easy-rsa/pki/ta.key"
    creates: "{{ openvpn_dir }}/easy/rsa/pki/ta.key"

- name: "OpenVPN | copy files to {{ openvpn_dir }}/server"
  copy:
    src: "{{ openvpn_dir }}/easy-rsa/pki/{{ item }}"
    dest: "{{ openvpn_dir }}/server/{{ item | basename }}"
    mode: "0644"
    remote_src: true
  loop:
    - ca.crt
    - dh.pem
    - ta.key
    - private/ca.key
    - private/server.key
    - issued/server.crt

- name: "OpenVPN | copy files to {{ openvpn_dir }}"
  copy:
    src: "{{ openvpn_dir }}/easy-rsa/pki/{{ item }}"
    dest: "{{ openvpn_dir }}/{{ item | basename }}"
    mode: "0644"
    remote_src: true
  loop:
    - ca.crt
    - ta.key
 
- name: OpenVPN | place server.conf
  template:
    src: server.conf.j2
    dest: "{{ openvpn_dir }}/server.conf"
    owner: root
    group: root
    mode: "0644"
  notify:
    - restart openvpn
