---
- name: configure postres master node
  become: true
  become_user: root
  hosts: db_master
  roles:
    - role: postgres
      vars:
        postgresql_role: master
        postgresql_master_group_name: db_master
        postgresql_replica_group_name: db_repli_cat
        postgresql_master_address: "192.168.56.221"
        postgresql_replica_address: 
          - "192.168.56.222"
        postgresql_replica_user: postgres

- name: configure postgres replica node
  become: true
  become_user: root
  hosts: db_repli_cat
  roles:
    - role: postgres
      vars:
        postgresql_role: replica
        postgresql_master_group_name: db_master
        postgresql_replica_group_name: db_repli_cat
        postgresql_master_address: "192.168.56.221"
        postgresql_replica_address: 
          - "192.168.56.222"
        postgresql_replica_user: postgres

